/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package lab07.test;
import com.github.javafaker.Faker;
import java.util.Random;

/**
 *
 * @author jiaenxu
 */
public class Lab07Test {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        Random rand = new Random();
        Faker faker = new Faker();
                       
       // ----------------------------------------------------
       //  Random Basic
        // ----------------------------------------------------
//        System.out.println("=== RANDOM BASIC DEMO ===");

//
//        int randomInt = 1 + rand.nextInt(10);  // 1–10
//        double randomDouble = rand.nextDouble(); // 0.0–1.0
//
//        System.out.println("Random integer (1–10): " + randomInt);
//        System.out.println("Random double (0–1): " + randomDouble);
//        System.out.println();
        
        // ----------------------------------------------------
        // RANDOM WITH PRODUCT LOOP — Using iteration
        // ----------------------------------------------------
//        System.out.println("=== RANDOM FOR PRODUCT PRICES AND QUANTITIES ===");
//
//        // Create 5 sample products using a loop
//        for (int i = 1; i <= 5; i++) {
//            String productName = "Product " + i;
//            String productId = "P" + faker.number().digits(5);
//            double floor = 10 + rand.nextInt(20);         // 10–30
//            double ceiling = floor + 10 + rand.nextInt(20); // 20–50 range
//            double target = (floor + ceiling) / 2;        // midpoint
//            Product p = new Product(productName,productId, floor, target, ceiling);
//
//            // Random actual selling price within the allowed range
//            double paidPrice = p.getFloorPrice()
//                    + rand.nextDouble() * (p.getCeilingPrice() - p.getFloorPrice());
//
//            int qty = 1 + rand.nextInt(5); // 1–5 items
//
//            System.out.println("Product: " + p.getName()
//                    + " | Floor: $" + String.format("%.2f", floor)
//                    + " | Ceiling: $" + String.format("%.2f", ceiling)
//                    + " | Qty: " + qty
//                    + " | Sold Price: $" + String.format("%.2f", paidPrice));
//        }
//        System.out.println();

        // ----------------------------------------------------
        // FAKER — Realistic business data
        // ----------------------------------------------------
//        System.out.println("=== FAKER BASIC DATA DEMO ===");
//
//        System.out.println("Customer Name: " + faker.name().fullName());
//        System.out.println("Company Name:  " + faker.company().name());
//        System.out.println("Address:       " + faker.address().fullAddress());
//        System.out.println("Product Name:  " + faker.commerce().productName());
//        System.out.println();
//
//        System.out.println("=== MULTIPLE CUSTOMERS GENERATED BY FAKER ===");
//        for (int i = 0; i < 3; i++) {
//            System.out.println("Customer " + (i + 1) + ": " + faker.name().fullName());
//        }
//        System.out.println();

        // ----------------------------------------------------
        // FUN FAKER THEMES — for creative examples
        // ----------------------------------------------------
//        System.out.println("=== FAKER FUN THEMES ===");
//
//        // Harry Potter
//        System.out.println("-- Harry Potter Theme --");
//        String character1 = faker.harryPotter().character();
//        String spell1 = faker.harryPotter().spell();
//
//        String character2 = faker.harryPotter().character();
//        String spell2 = faker.harryPotter().spell();
//
//        String character3 = faker.harryPotter().character();
//        String spell3 = faker.harryPotter().spell();
//
//        System.out.println(character1 + " casts " + spell1);
//        System.out.println(character2 + " casts " + spell2);
//        System.out.println(character3 + " casts " + spell3);
//        
//        
//        String test = faker.beer().name();
//        System.out.println("test : " + test);




//        // Create a new business instance (system setup)
//        Business biz = new Business();
//
//        // Call the high-level data generator with parameters:
//        // Parameters:
//        //    numSuppliers      = 3   → number of suppliers
//        //    numCustomers      = 4   → number of customers
//        //    ordersPerCustomer = 2   → each customer makes 2 orders
//        //    maxItemsPerOrder  = 3   → each order contains up to 3 items
//        biz.generateMockBusinessData(
//                3,   // suppliers
//                4,   // customers
//                2,   // orders per customer
//                3    // max items per order
//        );
//        
//        biz.printAllCustomers();
//        biz.printAllOrders();
//        biz.printAllSuppliers();




    }
    
}
